Inven_Management/Areas/InventoryManagement/Controllers/ProductAssaignController.cs
using Inven_Management.Areas.Config.Models;
using InventoryRepo.InventoryManagement;
using InventoryViewModel.Models;
using InventoryViewModel.ViewModel;
using JQueryDataTables.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Inven_Management.Areas.InventoryManagement.Controllers
{
    public class ProductAssaignController : Controller
    {
        #region Declare
        ProductAssaignRepo _repo = new ProductAssaignRepo();
        ProductRepo _prorepo = new ProductRepo();
        #endregion Declare
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult ProductDetail(string code, string Quantity, string UnitePrice, string Remarks)
        {
            Product vm = new Product();
            ProductAssignDetail provm = new ProductAssignDetail();
            vm = _prorepo.GETAllProducts().Where(m => m.Code == code).Single();
            provm.ProductId = vm.Id;
            provm.Code = vm.Code;
            //provm.Name = vm.Name + "-" + vm.ProductSizeName +vm.UOMName;
            provm.Quantity = Convert.ToDecimal(Quantity);
            provm.UnitePrice = vm.UnitePrice;
            provm.Remarks = Remarks;
             //provm = new ProductAssignDetail() {ProductId=vm.Products.Id, Code = provm.Code, Name = provm.Name, UnitePrice = provm.UnitePrice, Quantity = provm.Quantity };
             return PartialView("_ProductAssignDetail", provm);
        }
        public ActionResult ProductDetailEdit(string code, string Quantity, string UnitePrice, string Remarks)
        {
            Product vm = new Product();
            ProductAssignDetail provm = new ProductAssignDetail();
            vm = _prorepo.GETAllProducts().Where(m => m.Code == code).Single();
            provm.ProductId = vm.Id;
            provm.Code = vm.Code;
            //provm.Name = vm.Name + "-" + vm.ProductSizeName + vm.UOMName;
            provm.Quantity = Convert.ToDecimal(Quantity);
            provm.UnitePrice = vm.UnitePrice;
            provm.Remarks = Remarks;
            //provm = new ProductAssignDetail() {ProductId=vm.Products.Id, Code = provm.Code, Name = provm.Name, UnitePrice = provm.UnitePrice, Quantity = provm.Quantity };
            return PartialView("_ProductAssignDetailEdit", provm);
        }
        public ActionResult Create()
        {
            ProductAssaignVM vm = new ProductAssaignVM();
            ProductAssign proassgn = new ProductAssign();
            
            List<ProductAssignDetail> ProductAssignDetail = new List<ProductAssignDetail>();
            vm.ProductAssignDetail = ProductAssignDetail;
            vm.proassgn = proassgn;
            return View(vm);
        }
        [HttpPost]
        public ActionResult Create(ProductAssaignVM vm, string IsActive)
        {
            string[] result = new string[3];
            string mgs;
            try
            {
                //result = _repo.SaveAndEdit(vm);
                if (result[0] == "Fail")
                {
                    throw new ArgumentNullException("The expected data not found For Insert");
                }
                else
                {
                    string a = result[0] + "~" + result[1];
                    TempData["Msg"] = result[0] + "~" + result[1];
                    ViewBag.msg = result[0] + "~" + result[1];
                }
                mgs = result[0] + "~" + result[1];

            }
            catch (Exception ex)
            {
                TempData["Msg"] = result[0] + "~" + result[1] + " Error: " + ex.Message;
                mgs = result[0] + "~" + result[1];

                return Json(mgs, JsonRequestBehavior.AllowGet);
                //return RedirectToAction("Create",vm);
            }
            //return RedirectToAction("Index");
            return Json(mgs, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Edit()
        {
            ProductAssaignVM vm = new ProductAssaignVM();
            ProductAssign proassgn = new ProductAssign();

            List<ProductAssignDetail> ProductAssignDetail = new List<ProductAssignDetail>();
            vm.ProductAssignDetail = ProductAssignDetail;
            
            vm.proassgn = proassgn;
            return View(vm);
        }
        [HttpPost]
        public ActionResult Edit(ProductAssaignVM vm, string IsActive)
        {
            string[] result = new string[3];
            string mgs;
            try
            {
                //result = _repo.SaveAndEdit(vm);
                if (result[0] == "Fail")
                {
                    throw new ArgumentNullException("The expected data not found For Insert");
                }
                else
                {
                    string a = result[0] + "~" + result[1];
                    TempData["Msg"] = result[0] + "~" + result[1];
                    ViewBag.msg = result[0] + "~" + result[1];
                }
                mgs = result[0] + "~" + result[1];

            }
            catch (Exception ex)
            {
                TempData["Msg"] = result[0] + "~" + result[1] + " Error: " + ex.Message;
                mgs = result[0] + "~" + result[1];

                return Json(mgs, JsonRequestBehavior.AllowGet);
                //return RedirectToAction("Create",vm);
            }
            //return RedirectToAction("Index");
            return Json(mgs, JsonRequestBehavior.AllowGet);
        }
    }
}

Inven_Management/Areas/InventoryManagement/Views/ProductAssaign/Edit.cshtml
@{
    ViewBag.Title = "Edit";
}
@model InventoryViewModel.ViewModel.ProductAssaignVM
@using UIHelper.MVC
<style>
    .table > thead > tr > th, .table > tbody > tr > th, .table > tfoot > tr > th, .table > thead > tr > td, .table > tbody > tr > td, .table > tfoot > tr > td {
        padding: 0px !important;
    }
</style>
@using (Html.BeginForm("Create", "ProductAssaign", FormMethod.Post, new { Id = "upform" }))
{
    <div class="thinbox">
        <div class="th_thinbox">
            <p>Purchase List</p>
        </div>
        <div id="demo1">
            @Html.ValidationSummary(true)
            @Html.HiddenFor(model => model.proassgn.Id)
            <div class="row" style="">
                @*<div class="col-md-1">
                        <div class="editor-label">
                            &nbsp;
                        </div>
                        <div class="editor-field">
                        </div>
                    </div>*@
                <div class="col-md-2">
                    <div class="editor-label ">
                        @Html.LabelFor(model => model.proassgn.Code)
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(model => model.proassgn.Code, new { @placeholder = "Code", @class = "required form-control", @Onchage = "CheckCode(this)" })
                        @Html.ValidationMessageFor(model => model.proassgn.Code)
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="editor-label">
                        @Html.LabelFor(model => model.proassgn.InvoiecNo)
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(model => model.proassgn.InvoiecNo, new { @placeholder = "InvoiecNo", @class = " required form-control" })
                        @Html.ValidationMessageFor(model => model.proassgn.InvoiecNo)
                    </div>
                </div>

                <div class="col-md-2">
                    <div class="editor-label">
                        @Html.LabelFor(model => model.proassgn.ZoneOrAreaId)
                    </div>
                    <div class="editor-field">
                        @Html.SimpleDropDownFor(model => model.proassgn.ZoneOrAreaId, "/Config/DropDown/Supplier", new { @placeholder = " Product Category Name", @class = " form-control " })

                        @Html.ValidationMessageFor(model => model.proassgn.ZoneOrAreaId)
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="editor-label">
                        @Html.LabelFor(model => model.proassgn.EmployeeId)
                    </div>
                    <div class="editor-field">
                        @Html.SimpleDropDownFor(model => model.proassgn.EmployeeId, "/Config/DropDown/Employee", new { @placeholder = " Product Category Name", @class = " form-control" })

                        @Html.ValidationMessageFor(model => model.proassgn.EmployeeId)
                    </div>
                </div>
                @*<div class="col-md-2">
                        <div class="editor-label">
                            @Html.LabelFor(model => model.Date)
                        </div>
                        <div class="editor-field">
                            @Html.TextBoxFor(model => model.Date, new { @placeholder = "Date", @class = "customDatePicker required form-control" })
                            @Html.ValidationMessageFor(model => model.Date)
                        </div>
                    </div>*@

                <div class="col-md-2">
                    <div class="editor-label">
                        @Html.LabelFor(model => model.proassgn.Remarks)
                    </div>
                    <div class="editor-field">
                        @Html.TextAreaFor(model => model.proassgn.Remarks, new { @placeholder = "Remarks", @class = " form-control" })
                        @Html.ValidationMessageFor(model => model.proassgn.Remarks)
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="thinbox">
        <div class="th_thinbox">
            <p>Purchase List</p>
        </div>
        <div id="demo1">

            @Html.ValidationSummary(true)
            <div class="row" style="">
                <div class="col-md-2">
                    <div class="editor-label">
                        @Html.LabelFor(model => model.ProductAssignDetail.FirstOrDefault().Code)
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(model => model.ProductAssignDetail.FirstOrDefault().Code, new { @placeholder = "Code", @class = "required form-control code", @Onchage = "CheckCode(this)" })
                        @Html.ValidationMessageFor(model => model.ProductAssignDetail.FirstOrDefault().Code)
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="editor-label">
                        @Html.LabelFor(model => model.ProductAssignDetail.FirstOrDefault().Name)
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(model => model.ProductAssignDetail.FirstOrDefault().Name, new { @placeholder = "Name", @class = " Name required form-control", @readonly = "disable" })
                        @Html.ValidationMessageFor(model => model.ProductAssignDetail.FirstOrDefault().Name)
                    </div>
                </div>
                <div class="col-md-1">
                    <div class="editor-label">
                        @Html.LabelFor(model => model.ProductAssignDetail.FirstOrDefault().Quantity)
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(model => model.ProductAssignDetail.FirstOrDefault().Quantity, new { @placeholder = "Quantity", @class = "ppqty required number form-control" })
                        @Html.ValidationMessageFor(model => model.ProductAssignDetail.FirstOrDefault().Quantity)
                    </div>
                </div>
                <div class="col-md-1">
                    <div class="editor-label">
                        @Html.LabelFor(model => model.ProductAssignDetail.FirstOrDefault().UnitePrice)
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(model => model.ProductAssignDetail.FirstOrDefault().UnitePrice, new { @placeholder = "UnitePrice", @class = "ppunit number form-control", @readonly = "disable" })
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="editor-label">
                        @Html.LabelFor(model => model.ProductAssignDetail.FirstOrDefault().Remarks)
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(model => model.ProductAssignDetail.FirstOrDefault().Remarks, new { @placeholder = "Remarks", @class = " form-control" })
                        @Html.ValidationMessageFor(model => model.ProductAssignDetail.FirstOrDefault().Remarks)
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="editor-label">
                        &nbsp;
                    </div>
                    <button type="button" title="Save Data" class="i-btn-add AddRowIndent" id="addrow"> Addrow</button>
                </div>
            </div>
        </div>
    </div>

    <table class="table table-responsive table-striped table-hover display">
        <thead>
            <tr>
                <th>Action</th>
                <th>Code</th>
                <th>Name</th>
                <th>Quantity</th>
                <th>UnitPrice</th>
                <th>Amount</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.ProductAssignDetail)
            {
                Html.RenderPartial("_ProductAssignDetailEdit", item);
            }
        </tbody>
        <tfoot>
            <tr>
                <td></td>
                <td></td>
                <td>Total Quantity =</td>
                <td><input type="text" readonly="readonly" class="totaolqty form-control" /></td>
                <td><b> Total =</b></td>
                <td><input type="text" readonly="readonly" class="result form-control" /> </td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>Grand Total</td>
                <td><input type="text" readonly="readonly" class="grandTotal right form-control" /></td>
            </tr>
        </tfoot>
    </table>

    <div class="row">
        <div class="col-md-3">
            <div class="editor-label">
                &nbsp;
            </div>
            <div class="editor-field">
                <button type="button" title="Save Data" id="sub" class="i-btn-save"> Save</button>
            </div>
        </div>
    </div>
}
<script>
    $(document).ready(function () {
        $(".simpledrop").select2();
        calculation();

        $(".code").autocomplete({
            source: '@Url.Action("Product", "Autocomplete", new { area = "Config" })', minLength: 1,})
    $(".code").click(function () {
        autocom();
    });
    $(".code").change(function () {
        autocom();
    });
    function autocom() {
            var value = $(".code").val();
            var code = $(".code").val(value.split('-')[0]);
            $(".Name").val(value.split('-')[1] + "-" + value.split('-')[2]);

    }
        $("table").hide();

                $("#Products_Code").val('');
                $("#Products_Code").val('');
                if(
                $("#Code").val()!= '')
                {
                    $("table").show();
                }
                $("#addrow").click(function () {
                    var code = $(".code").val();
                    var exit = true;
                    $(".pa").each(function (i, item) {
                        var el = $(this);

                        var tcode = el.closest("tr").find(".pcode").val();
                        if (code == tcode) {
                            exit = false;
                            alert("this Product Already Add in below List");
                        }
                    })
            var Quantity = $(".ppqty").val();
            var UnitePrice = $(".ppunit").val();
            var remarks = $("#Remarks").val();
            if (exit == true) {
                var url = "/InventoryManagement/ProductAssaign/ProductDetailEdit?code=" + code + "&Quantity=" + Quantity + "&UnitePrice=" + UnitePrice + "&Remarks=" + remarks;
                $.get(url, function (data) {
                    $("table tbody").append(data);
                    calculation();
                    //$(".Name").val('');
                    //$(".code").val('');
                    //$(".ppqty").val('');
                    //$(".ppunit").val('');
                    //$("#Remarks").val("");
                    $("table").show();

                });
            }
                });

        $(".Edit-row").click(function () {
            calculation();

        });
        $("#sub").click(function () {
            var datas = $("#upform").serialize();
            var url = $("form").attr("action");
            $.post(url, datas, function (data, status) {
                window.location.reload();
                if (status == "success") {
                    ShowResult(data);
                }
         });
        });

        $(".TotalDiscount,.grandTotal").change(function () {
            calculation();
        });
        $(function () {
            calculation();

        });
        function calculation() {
            var result= 0;
            var totaolqty = 0;
            var totaldise = 0;
            var ttotal = 0;
            var tdis = 0;
            $(".pa").each(function (i, item) {
                var el = $(this);
                var qty, unit, disc, amount = 0;
                qty = el.closest("tr").find(".qty").val();
                unit = el.closest("tr").find(".unit").val();
                amount = (parseFloat(qty) * parseFloat(unit));
                el.closest("tr").find(".amount").val(amount);
                totaolqty += parseFloat(qty);
                result += amount;
            });
            $('.result').val(result);
            $('.totaolqty').val(totaolqty);
            ttotal =result
            $(".grandTotal").val(ttotal);
        }
        $('.qty,.unit,.disc').keyup(function () {
            calculation();
        });
    $(".number").change(function () {
        if (!$.isNumeric($(this).val())) {
            $(this).val(" ");
            alert("this not be Numeric")
        }
    });
    $(".Edit-row").click(function () {
        var a = $(this).parents().parents().children().find(".qty").val();
        $(".code").val($(this).parents().parents().children().find(".pcode").val());
        $(".Name").val($(this).parents().parents().children().find(".pname").val());
        $(".ppqty").val($(this).parents().parents().children().find(".qty").val());
        $(".ppunit").val($(this).parents().parents().children().find(".unit").val());
        $(".ppdis").val($(this).parents().parents().children().find(".disc").val());
        $(this).closest('.pa').remove();
        calculation();
    });
    $(".remove-row").click(function () {
        Ask("Are you sure to delete this file!", function () {
            $(this).closest('tr.pa:first').remove();
            calculation();

        }, function () { });
    });
    });


</script>

Inven_Management/Areas/InventoryManagement/Views/ProductAssaign/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<div class="headrow">
    <button type="button" title="Add New Product" data-url="/InventoryManagement/ProductAssaign/Create" onclick="GoTo(this)" id="" class="i-btn-add "> New</button>
    <button type="button" title="Delete Product" data-url="/InventoryManagement/ProductAssaign/Delete" onclick="deletedData(this, 'myDataTable');" id="" class="i-btn-remove"> Delete</button>
</div>

Inven_Management/Areas/InventoryManagement/Views/ProductAssaign/_ProductAssignDetail.cshtml
@model InventoryViewModel.Models.ProductAssignDetail
@using UIHelper.MVC

<tr class="pa">
@using (Html.BeginCollectionItem("ProductAssignDetail"))
{
    @Html.HiddenFor(model=>model.Id);
    @Html.HiddenFor(m => m.ProductId);
    <td style="width:10%"><a class="Edit-row i-btn-edit-row"></a><a class="remove-row i-btn-remove-row"></a></td>
    <td style="width:10%">@Html.TextBoxFor(model => model.Code, new { @placeholder = " Product Code", @class = "pcode form-control", @readonly = "disable" })</td>
    <td style="width:25%">@Html.TextBoxFor(model => model.Name, new { @placeholder = " Product Name", @class = "pname form-control", @readonly = "disable" })</td>
    <td style="width:8%">@Html.TextBoxFor(model => model.Quantity, new { @placeholder = " Product Quantity", @class = "qty form-control", @readonly = "disable" })</td>
    <td style="width:8%">@Html.TextBoxFor(model => model.UnitePrice, new { @placeholder = " Product UnitePrice", @class = "unit form-control", @readonly = "disable" })</td>
    <td style="width:8%">@Html.TextBoxFor(model => model.Returns, new { @placeholder = " Product Returns", @class = "retun form-control" })</td>
    <td style="width:8%">@Html.TextBoxFor(model => model.Replace, new { @placeholder = " Product Replace", @class = "rep form-control" })</td>
    <td style="width:8%">@Html.TextBoxFor(model => model.Slup, new { @placeholder = " Product Slup", @class = "slups form-control" })</td>
    <td style="width:20%">@Html.TextBoxFor(model => model.Discount, new { @placeholder = " Product Amount", @class = "amount right form-control", @readonly = "disable" })</td>
}
</tr>
<script>
    
</script>

Inven_Management/Areas/InventoryManagement/Views/ProductAssaign/_ProductAssignDetailEdit.cshtml
@model InventoryViewModel.Models.ProductAssignDetail
@using UIHelper.MVC
<tr class="pa">
@using (Html.BeginCollectionItem("ProductAssignDetail"))
{
    @Html.HiddenFor(model=>model.Id);
    @Html.HiddenFor(m => m.ProductId);
    <td style="width:10%"><a class="Edit-row i-btn-edit-row"></a><a class="remove-row i-btn-remove-row"></a></td>
    <td style="width:10%">@Html.TextBoxFor(model => model.Code, new { @placeholder = " Product Code", @class = "pcode form-control",@readonly="disable" })</td>
    <td style="width:25%">@Html.TextBoxFor(model => model.Name, new { @placeholder = " Product Name", @class = "pname form-control", @readonly = "disable" })</td>
    <td style="width:8%">@Html.TextBoxFor(model => model.Quantity, new { @placeholder = " Product Quantity", @class = "qty form-control", @readonly = "disable" })</td>
    <td style="width:8%">@Html.TextBoxFor(model => model.UnitePrice, new { @placeholder = " Product UnitePrice", @class = "unit form-control", @readonly = "disable" })</td>
    <td style="width:8%">@Html.TextBoxFor(model => model.Returns, new { @placeholder = " Product Returns", @class = "retun form-control"})</td>
    <td style="width:8%">@Html.TextBoxFor(model => model.Replace, new { @placeholder = " Product Replace", @class = "rep form-control" })</td>
    <td style="width:8%">@Html.TextBoxFor(model => model.Slup, new { @placeholder = " Product Slup", @class = "slups form-control" })</td>
    <td style="width:20%">@Html.TextBoxFor(model => model.Discount, new { @placeholder = " Product Amount", @class = "amount right form-control", @readonly = "disable" })</td>
}
</tr>