Inven_Management/Areas/InventoryManagement/Controllers/StockController.cs
using InventoryRepo.InventoryManagement;
using InventoryViewModel.Models;
using InventoryViewModel.ViewModel;
using JQueryDataTables.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Inven_Management.Areas.InventoryManagement.Controllers
{
    public class StockController : Controller
    {
        #region Declare
        StockRepo _repo = new StockRepo();
        InventoryEntities _context = new InventoryEntities();
        #endregion Declare
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult _index(JQueryDataTableParamModel param)//EmployeeId
        {
            #region Column Search
            var idFilter = Convert.ToString(Request["sSearch_0"]);
            var InvoiceFilter = Convert.ToString(Request["sSearch_1"]);
            var DateFilter = Convert.ToString(Request["sSearch_2"]);
            var SupplierFilter = Convert.ToString(Request["sSearch_3"]);
            var TotalPriceFilter = Convert.ToString(Request["sSearch_4"]);
            #endregion Column Search

            var getAllData = _repo.GETAllStockstor();
            IEnumerable<StockVM> filteredData;
            //Check whether the companies should be filtered by keyword
            if (!string.IsNullOrEmpty(param.sSearch))
            {
                //Optionally check whether the columns are searchable at all 
                var isSearchable1 = Convert.ToBoolean(Request["bSearchable_1"]);
                var isSearchable2 = Convert.ToBoolean(Request["bSearchable_2"]);
                var isSearchable3 = Convert.ToBoolean(Request["bSearchable_3"]);
                var isSearchable4 = Convert.ToBoolean(Request["bSearchable_4"]);
                filteredData = getAllData.Where(c => isSearchable1 && c.EmployeeName.ToLower().Contains(param.sSearch.ToLower())
                               || isSearchable2 && c.ProductCode.ToLower().Contains(param.sSearch.ToLower())
                               || isSearchable3 && c.ProductName.ToString().ToLower().Contains(param.sSearch.ToLower())
                               || isSearchable3 && c.ProductName.ToString().ToLower().Contains(param.sSearch.ToLower())
                               );
            }
            else
            {
                filteredData = getAllData;
            }
            #region Column Filtering
            if (InvoiceFilter != "" || DateFilter != "" || SupplierFilter != "")
            {
                filteredData = getAllData.Where(c => (InvoiceFilter == "" || c.SupplierName.ToLower().Contains(InvoiceFilter.ToLower()))
                                            && (SupplierFilter == "" || c.SupplierName.ToString().ToLower().Contains(SupplierFilter.ToLower()))
                                            && (TotalPriceFilter == "" || c.UnitPrice.ToString().ToLower().Contains(TotalPriceFilter.ToLower())));
            }
            #endregion Column Filtering
            var isSortable_1 = Convert.ToBoolean(Request["bSortable_1"]);
            var isSortable_2 = Convert.ToBoolean(Request["bSortable_2"]);
            var isSortable_3 = Convert.ToBoolean(Request["bSortable_3"]);
            var isSortable_4 = Convert.ToBoolean(Request["bSortable_4"]);
            var sortColumnIndex = Convert.ToInt32(Request["iSortCol_0"]);
            Func<StockVM, string> orderingFunction = (c => sortColumnIndex == 1 && isSortable_1 ? c.SupplierName :
                                                           sortColumnIndex == 3 && isSortable_2 ? c.SupplierName.ToString() :
                                                           sortColumnIndex == 4 && isSortable_3 ? c.TotalPrice.ToString() : "");
            var sortDirection = Request["sSortDir_0"]; // asc or desc
            if (sortDirection == "asc")
                filteredData = filteredData.OrderBy(orderingFunction);
            else
                filteredData = filteredData.OrderByDescending(orderingFunction);
            var displayedCompanies = filteredData.Skip(param.iDisplayStart).Take(param.iDisplayLength);
            var result = from c in displayedCompanies
                         select new[] { 
                 //Convert.ToString(c.Id)
                c.ProductName+"-"+c.ProductCode
               // ,c.TotalQuantity.ToString()
                ,c.FinalUnitPrice.ToString()
                //,(c.TotalPrice=c.TotalQuantity+c.FinalUnitPrice).ToString()
                //,c.TotalReplace.ToString()
                //,c.TotalReturn.ToString()
                //,c.TotalSlup.ToString()
                         };
            return Json(new
            {
                sEcho = param.sEcho,
                iTotalRecords = getAllData.Count()
                ,
                iTotalDisplayRecords = filteredData.Count()
                ,
                aaData = result
            }, JsonRequestBehavior.AllowGet);
        }
    }
}

Inven_Management/Areas/InventoryManagement/Views/Stock/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<div class="thinbox">
    <div class="th_thinbox">
        <p>Stock List</p>
    </div>
    <p></p>
    <div class="row">
        <div id="container">
            <div id="demo">
                <table id="myDataTable" class="display">
                    <thead>
                        <tr>
                           
                            <th>Product Name</th>
                            <th>Total Quantity</th>
                            <th>Unit Price</th>
                            <th>Total Price</th>
                            @*<th>Total Replace</th>
                            <th>Total Return</th>
                            <th>Total Slup</th>*@
                        </tr>
                        <tr>
                            
                            <th>Product Name</th>
                            <th>Total Quantity</th>
                            <th>Unit Price</th>
                            <th>Total Price</th>
                           
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@section head{
    <script>
        $(document).ready(function () {
            var oTable = $('#myDataTable').dataTable({
                "bServerSide": true,
                "sAjaxSource": "/InventoryManagement/Stock/_index",
                "bProcessing": true,
                "aLengthMenu": tablelength(),
                "bJqueryUI": true,
                "bAutoWidth": false,
                "aoColumns": [
                    
                                 { "sName": "ProductName", "sWidth": "20%" }
                                , { "sName": "TotalQuantity", "sWidth": "10%" }
                                , { "sName": "UnitPrice", "sWidth": "10%" }
                                , { "sName": "TotalPrice", "sWidth": "10%" }
                ]
            });
            oTable.columnFilter({
                sPlaceHolder: "head:after",
                aoColumns: [
                            { type: "text" }
                           , { type: "text" }
                           , { type: "text" }
                           , { type: "text" }
                ]
            });
            SelectAllForDelete();
            $("#Code").keyup(function () {
                $("#Code").parent().find("p").remove();
                var url = "@Url.Action("check", "Stock", new { area = "InventoryManagement" })"
                var code = $(this).val();
                $.get("@Url.Action("check", "Stock", new { area = "InventoryManagement" })", { code: code }, function (data, status) {
                    $("#Code").parent().append('<p class="RequiredField" style="color:red;" >' + data + '</p>');
                });
            });
            $("#Name").keyup(function () {
                $("#Name").parent().find("p").remove();
                var url = "@Url.Action("check", "Stock", new { area = "InventoryManagement" })"
                var name = $(this).val();
                $.get("@Url.Action("check", "Stock", new { area = "InventoryManagement" })", { name: name }, function (data, status) {
                    $("#Name").parent().append('<p class="RequiredField" style="color:red;" >' + data + '</p>');
                });
            });
        });
    </script>
}