Inven_Management/Areas/Config/Controllers/ProductTypeController.cs
using InventoryRepo.InventoryManagement;
using InventoryViewModel.Models;
using JQueryDataTables.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Inven_Management.Areas.Config.Controllers
{
    public class ProductTypeController : Controller
    {
        #region Declare
        ProductTypeRepo _repo = new ProductTypeRepo();
        #endregion Declare
        public ActionResult Index()
        {
            ProductType vm = new ProductType();
            vm.IsActive = true;
            return View(vm);
        }

        //public JsonResult _index(JQueryDataTableParamModel param ) {
        //    IEnumerable<ProductType> vm = _repo.GETAllProductType;

        //    return Json(vm,JsonRequestBehavior.AllowGet);
        //}
        public ActionResult _index(JQueryDataTableParamModel param)//EmployeeId
        {
            #region Column Search
            var idFilter = Convert.ToString(Request["sSearch_0"]);
            var codeFilter = Convert.ToString(Request["sSearch_1"]);
            var nameFilter = Convert.ToString(Request["sSearch_2"]);
            var isActiveFilter = Convert.ToString(Request["sSearch_3"]);
            var RemarkFilter = Convert.ToString(Request["sSearch_4"]);

            var isActiveFilter1 = isActiveFilter.ToLower() == "y" ? true.ToString() : false.ToString();
            #endregion Column Search

            var getAllData = _repo.GETAllProductType;
            IEnumerable<ProductType> filteredData;
            //Check whether the companies should be filtered by keyword
            if (!string.IsNullOrEmpty(param.sSearch))
            {

                //Optionally check whether the columns are searchable at all 
                var isSearchable1 = Convert.ToBoolean(Request["bSearchable_1"]);
                var isSearchable2 = Convert.ToBoolean(Request["bSearchable_2"]);
                var isSearchable3 = Convert.ToBoolean(Request["bSearchable_3"]);
                var isSearchable4 = Convert.ToBoolean(Request["bSearchable_4"]);

                filteredData = getAllData
                   .Where(c => isSearchable1 && c.Name.ToLower().Contains(param.sSearch.ToLower())
                               ||
                               isSearchable2 && c.Code.ToLower().Contains(param.sSearch.ToLower())
                               ||
                               isSearchable4 && c.Remarks.ToLower().Contains(param.sSearch.ToLower()));
            }
            else
            {
                filteredData = getAllData;
            }
            #region Column Filtering
            if (codeFilter != "" || nameFilter != "" || isActiveFilter != "")
            {
                filteredData = getAllData
                                .Where(c => (codeFilter == "" || c.Code.ToLower().Contains(codeFilter.ToLower()))
                                            &&
                                            (nameFilter == "" || c.Name.ToLower().Contains(nameFilter.ToLower()))
                                            &&
                                            (isActiveFilter == "" || c.IsActive.ToString().ToLower().Contains(isActiveFilter1.ToLower()))
                                            &&
                                            (RemarkFilter == "" || c.Remarks.ToLower().Contains(RemarkFilter.ToLower()))
                                        );
            }

            #endregion Column Filtering

            var isSortable_1 = Convert.ToBoolean(Request["bSortable_1"]);
            var isSortable_2 = Convert.ToBoolean(Request["bSortable_2"]);
            var isSortable_3 = Convert.ToBoolean(Request["bSortable_3"]);
            var isSortable_4 = Convert.ToBoolean(Request["bSortable_4"]);
            var sortColumnIndex = Convert.ToInt32(Request["iSortCol_0"]);
            Func<ProductType, string> orderingFunction = (c => sortColumnIndex == 1 && isSortable_1 ? c.Name :
                                                           sortColumnIndex == 2 && isSortable_2 ? c.Code :
                                                           sortColumnIndex == 3 && isSortable_3 ? c.Name :
                                                           sortColumnIndex == 3 && isSortable_4 ? c.Remarks :
                                                           "");

            var sortDirection = Request["sSortDir_0"]; // asc or desc
            if (sortDirection == "asc")
                filteredData = filteredData.OrderBy(orderingFunction);
            else
                filteredData = filteredData.OrderByDescending(orderingFunction);

            var displayedCompanies = filteredData.Skip(param.iDisplayStart).Take(param.iDisplayLength);
            var result = from c in displayedCompanies
                         select new[] { Convert.ToString(c.Id),
                
                c.Code, c.Name
                , Convert.ToString(c.IsActive == true ? "Y" : "N") 
                
                ,c.Remarks };
            return Json(new
            {
                sEcho = param.sEcho,
                iTotalRecords = getAllData.Count(),
                iTotalDisplayRecords = filteredData.Count(),
                aaData = result
            },
                        JsonRequestBehavior.AllowGet);
        }

        //public ActionResult Create()
        //{
        //    ProductType vm = new ProductType();
        //    return PartialView("Create", vm);
        //}
        [HttpPost]
        public ActionResult Create(ProductType vm, string IsActive)
        {
            string[] result = new string[3];
            try
            {
                result = _repo.SaveAndEdit(vm);
                if (result[0] == "Fail")
                {
                    throw new ArgumentNullException("The expected data not found For Insert");
                }
                else
                {
                    string a = result[0] + "~" + result[1];
                    TempData["Msg"] = result[0] + "~" + result[1];
                    ViewBag.msg = result[0] + "~" + result[1];
                }
            }
            catch (Exception ex)
            {
                TempData["Msg"] = result[0] + "~" + result[1] + " Error: " + ex.Message;
                ViewBag.msg = result[0] + "~" + result[1];
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
        public ActionResult Edit(int Id)
        {
            ProductType vm = new ProductType();
            vm = _repo.GetSigle(Id);
            return View("Index", vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ProductType vm)
        {
            string[] result = new string[3];
            try
            {
                result = _repo.SaveAndEdit(vm);
                if (result[0] == "Fail")
                {
                    throw new ArgumentNullException("The expected data not found For Insert");
                }

                TempData["Msg"] = result[0] + "~" + result[1];
            }
            catch (Exception ex)
            {
                ViewBag.fail = result[0] + " " + result[1] + " Error: " + ex.Message;
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
        public ActionResult Delete(string Ids)
        {
            string[] a = Ids.Split('~');
            string[] result = new string[3];
            try
            {
                result = _repo.Delete(a);
                if (result[0] == "Fail")
                {
                    throw new ArgumentNullException("The expected data not found For Delete");
                }
                TempData["Msg"] = result[0] + "~" + result[1];
            }
            catch (Exception ex)
            {
                TempData["Msg"] = result[0] + "~" + result[1] + " Error: " + ex.Message;
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
        public String check(string code, string name)
        {
            var data = _repo.GETbySearch(null, name, code);
            if (data.Count() == 0)
            {
                return "That value is available!";
            }
            else
            {
                return "This value Already Exit";
            }
        }
        public JsonResult Edits(int Id)
        {
            ProductType vm = _repo.GetSigle(Id);
            return Json(vm, JsonRequestBehavior.AllowGet);
        }

    }
}

Inven_Management/Areas/Config/Views/ProductType/Index.cshtml
@model InventoryViewModel.Models.ProductType
@{
    ViewBag.Title = "Index";
}
<div class="creates">

    @Html.Partial("_create", Model);
</div>

<div class="headrow">
    <button type="button" title="Add New ProductType" data-url="/Config/Product Type/Create" onclick="GoTo(this)" id="" class="i-btn-add "> New</button>
    <button type="button" title="Delete ProductType" data-url="/Config/Product Type/Delete" onclick="deletedData(this, 'myDataTable');" id="" class="i-btn-remove"> Delete</button>
</div>
<div class="thinbox">
    <div class="th_thinbox">
        <p>Product Type List</p>
    </div>
    <p></p>
    <table id="myDataTable" class="display">
        <thead>
            <tr>
                <th>
                    <input type="checkbox" class="chkAll" />Select All
                </th>
                <th>Code</th>
                <th>Name</th>
                <th>Active</th>
                <th>Remarks</th>
            </tr>
            <tr>
                <th style="padding-left: 2.5%">Actions</th>
                <th>Code</th>
                <th>Name</th>
                <th>Active</th>
                <th>Remarks</th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>
</div>
<div class="headrow">
    <button type="button" title="Add New ProductType" data-url="/Config/ProductType/Create" id="" class="btnCreate i-btn-add "> New</button>
    <button type="button" title="Delete ProductType" data-url="/Config/ProductType/Delete" onclick="deletedData(this, 'myDataTable');" id="" class="i-btn-remove"> Delete</button>
</div>
@section head{
    <script>
        $(document).ready(function () {
            var oTable = $('#myDataTable').dataTable({
                "bServerSide": true,
                "sAjaxSource": "/Config/ProductType/_index",
                "bProcessing": true,
                "aLengthMenu": tablelength(),
                "bJqueryUI": true,
                "bAutoWidth": false,
                "aoColumns": [
                                {
                                    "sName": "Id",
                                    "bSearchable": false,
                                    "bSortable": false,
                                    "sWidth": "13%",
                                    "fnRender": function (oObj) {
                                        return ' <input onclick="CheckAll(this)" type="checkbox" data-Id="' + oObj.aData[0] + '">&nbsp; <a title="Click on for Edit" style="text-decoration:none;" href=\"/Config/ProductType/Edit/' + oObj.aData[0] + '\"  class=" i-btn-edit-row"></a>' +
                                        '&nbsp; <a title="Click on for Delete" style="text-decoration:none;"  data-url="/Config/ProductType/Delete" onclick="deletedData(this, myDataTable,' + oObj.aData[0] + ');"  class="i-btn-remove-row"></a>';
                                    }
                                }
                                , { "sName": "Code", "sWidth": "10%" }
                                , { "sName": "Name", "sWidth": "10%" }
                                , { "sName": "Active", "sWidth": "10%" }
                                , { "sName": "Remarks", "sWidth": "10%" }
                ]
            });
            oTable.columnFilter({
                sPlaceHolder: "head:after",
                aoColumns: [{ type: "checkbox", "sClass": "chkAll" }
                           , { type: "text" }
                           , { type: "text" }
                           , { type: "text" }
                           , { type: "text" }
                ]
            });
            SelectAllForDelete();
            $("#Code").keyup(function () {
                $("#Code").parent().find("p").remove();
                var url = "@Url.Action("check", "ProductType", new { area = "Config" })"
                var code = $(this).val();
                $.get("@Url.Action("check", "ProductType", new { area = "Config" })", { code: code }, function (data, status) {
                    $("#Code").parent().append('<p class="RequiredField" style="color:red;" >' + data + '</p>');
                });
            });
            $("#Name").keyup(function () {
                $("#Name").parent().find("p").remove();
                var url = "@Url.Action("check", "ProductType", new { area = "Config" })"
                var name = $(this).val();
                $.get("@Url.Action("check", "ProductType", new { area = "Config" })", { name: name }, function (data, status) {
                    $("#Name").parent().append('<p class="RequiredField" style="color:red;" >' + data + '</p>');
                });
            });
        });
    </script>
}

Inven_Management/Areas/Config/Views/ProductType/_create.cshtml
@model InventoryViewModel.Models.ProductType

<div class="thinbox">
    <div class="th_thinbox">
        <p>Product Type List</p>
    </div>
    <p></p>
    <div class="row">
        @using (Html.BeginForm("Create", "ProductType", FormMethod.Post, new { @area = "Config", enctype = "multipart/form-data", @Id = "upfrom" }))
        {
            @Html.ValidationSummary(true)
            @Html.HiddenFor(model => model.Id)
            <div class="row" style="">
                <div class="col-md-1">
                    <div class="editor-label">
                        &nbsp;
                    </div>
                    <div class="editor-field">
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="editor-label">
                        @Html.LabelFor(model => model.Code)
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(model => model.Code, new { @placeholder = "Code", @class = "required form-control code", @Onchage = "CheckCode(this)" })
                        @Html.ValidationMessageFor(model => model.Code)
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="editor-label">
                        @Html.LabelFor(model => model.Name)
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(model => model.Name, new { @placeholder = "Name", @class = " required form-control" })
                        @Html.ValidationMessageFor(model => model.Name)
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="editor-label">
                        @Html.LabelFor(model => model.IsActive)
                    </div>
                    <div class="editor-field">
                        @Html.CheckBox("IsActive", true, new { @class = "form-control", @checked = "checked" });
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="editor-label">
                        @Html.LabelFor(model => model.Remarks)
                    </div>
                    <div class="editor-field">
                        @Html.TextAreaFor(model => model.Remarks, new { @placeholder = "Remarks", @class = " form-control" })
                        @Html.ValidationMessageFor(model => model.Name)
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="editor-label">
                        &nbsp;
                    </div>
                    <div class="editor-field">
                        <button type="submit" title="Save Data" onclick="pageSubmit('upfrom');" class="i-btn-save"> Save</button>
                        <button type="button" title="Cancel Data" onclick="controllerBKE.CancelBlack();" class="i-btn-cancel"> Cancel</button>

                    </div>
                </div>
            </div>
        }
    </div>
</div>